### ISSUE TITLE
Name the logs file with test context?

### ISSUE THREAD

**Issue by n3wscott** [chainguard-dev/actions#116]
We upload logs from e2e tests. But we also run matrix jobs. If we fail more than one e2e test, we get a single `logs.tar.gz` file. and ... I have no idea which run it is tied to. I assume it is the last one.  Can we name the logs artifact with some of the test name?

**Comment by cpanato** [comment]
yes, the last one that is submitted, will fix that

**Comment by cpanato** [comment]
looks like it is already fixed
closing
