### ISSUE TITLE
Add ability to specify v1.7.x style for knative version.

### ISSUE THREAD

**Issue by vaikas** [chainguard-dev/actions#154]
Sometimes it's desireable to not have to specify the exact version of the, say knative version. Some reasons are:
 * The components don't all have that specific version
 * you really don't care which minor version it is

In #153 I added a latest that will pull the latest version for each, but again, it might be nice to go back to an older version like v1.6.x.

**Comment by cpanato** [comment]
PR: https://github.com/chainguard-dev/actions/pull/162
