### ISSUE TITLE
setup-registry fails (without failing) when setup-go has not been run

### ISSUE THREAD

**Issue by mattmoor** [chainguard-dev/actions#228]
<img width="804" alt="image" src="https://user-images.githubusercontent.com/2442466/235578468-d8fd80c4-7f37-4e92-941a-9209f95d55bb.png">

**Comment by mattmoor** [comment]
cc @imjasonh @jonjohnsonjr

**Comment by imjasonh** [comment]
https://github.com/chainguard-dev/actions/pull/229
